### ISSUE TITLE
What's Deeeplang?

### ISSUE THREAD

**Issue by ice1000** [deeplang-org/deeplang-type-system#14]
I found it in the README. Is it related to deeplang?

**Comment by Guest0x0** [comment]
Yes. The development of everything from parser to codegen (to VM bytecode, which lives in the deeplang repo) happens here.

**Comment by ice1000** [comment]
> Yes. The development of everything from parser to codegen (to VM bytecode, which lives in the deeplang repo) happens here.

Coool! I expected it to be a typo but it turns out to be intensional

**Comment by Guest0x0** [comment]
No. It's a typo, and me careless enough to not notice the issue title :(
